### ISSUE TITLE
sophie-lu-speak-the-code

### ISSUE THREAD

**Issue by Sophie724** [Sophie724/components-on-a-grid#1]
@thatkidmadrid
Hi Christian,
I have attached my assignment. Thank you.

Regard,
Sophie

[sophie-lu-speak-your-code.m4a.zip](https://github.com/Sophie724/components-on-a-grid/files/7221449/sophie-lu-speak-your-code.m4a.zip)

**Comment by thatkidmadrid** [comment]
looks good and sounds good

I did notice that the spacing between the figures is a bit off, may be because you're using `display: flex` in the `main`, which is not necessary, but you were on the right track using `gap`, it just belongs in the grid, and not the flex that you added
